# -*- coding: utf-8 -*-
"""plot graphs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O07prYz7pmJf7sHIBIuTlT9_exaqw5JW
"""

import matplotlib.pyplot as plt

# Data from the provided JSON
data = [
    {"epoch": 1.0, "loss": 2.5543},
    {"epoch": 2.0, "loss": 0.8238},
    {"epoch": 3.0, "loss": 0.758},
    {"epoch": 4.0, "loss": 0.7242},
    {"epoch": 5.0, "loss": 0.7318},
    {"epoch": 6.0, "loss": 0.7167},
    {"epoch": 7.0, "loss": 0.6949},
    {"epoch": 8.0, "loss": 0.698},
    {"epoch": 9.0, "loss": 0.69},
    {"epoch": 10.0, "loss": 0.6856},
]

# Extract epochs and losses
epochs = [item["epoch"] for item in data]
losses = [item["loss"] for item in data]

# Create the plot
plt.figure(figsize=(8, 5))  # Set the figure size
plt.bar(epochs, losses, color='black')
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Loss vs Epoch of Experiment 9.1")
plt.grid(False)  # Add grid lines for better readability

# Display the plot
plt.show()

#experiment 13
import matplotlib.pyplot as plt

# Data from the provided JSON
data13 = [
    {"epoch": 1.0 ,"loss": 0.8137},
    {"epoch": 2.0, "loss": 0.7861 },
    {"epoch": 3.0, "loss": 0.7495 },


]

# Extract epochs and losses
epochs = [item["epoch"] for item in data13]
losses = [item["loss"] for item in data13]

# Create the plot
plt.figure(figsize=(8, 5))  # Set the figure size
plt.bar(epochs, losses, color='black' )  # Plot the data with markers and line
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Loss vs Epoch of Experiment 9.2 ")
#plt.grid(True)  # Add grid lines for better readability

# Display the plot
plt.show()

#experiment 14
import matplotlib.pyplot as plt

# Data from the provided JSON
data14 = [
    {"epoch": 1.0 ,"loss": 2.8996},
    {"epoch": 2.0, "loss": 2.3872},
    {"epoch": 3.0, "loss": 2.2837 },
    {"epoch": 4.0, "loss": 2.1271},
    {"epoch": 5.0, "loss": 2.3887 }
]

# Extract epochs and losses
epochs = [item["epoch"] for item in data14]
losses = [item["loss"] for item in data14]

# Create the plot
plt.figure(figsize=(8, 5))  # Set the figure size
plt.bar(epochs, losses, color='black' )  # Plot the data with markers and line
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Loss vs Epoch from finetuning Experiment 10")
#plt.grid(True)  # Add grid lines for better readability

# Display the plot
plt.show()







data3 = [

    {
      "epoch": 1.0,

      "loss": 1.799

    },

       {
      "epoch": 2.0,
           "loss": 1.5895
         },



    {
      "epoch": 3.0,

      "loss": 1.2106

    },




    {
      "epoch": 4.01,

      "loss": 1.1454

    },



{
      "epoch": 5.0,
"loss": 1.0777},


]

import matplotlib.pyplot as plt

# Data from the provided JSON

# Extract epochs and losses
epochs = [item["epoch"] for item in data3]
losses = [item["loss"] for item in data3]

# Create the plot
#plt.figure(figsize=(8, 5))  # Set the figure size
plt.bar(epochs, losses, color='black')
#plt.plot(epochs, losses, marker='o', linestyle='-')  # Plot the data with markers and line
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Loss vs Epoch while Pre-Training BART ")
plt.grid(True)  # Add grid lines for better readability

# Display the plot
plt.show()



import matplotlib.pyplot as plt

# Data from the provided JSON
data = [
    {"epoch": 1.0 ,"loss": 1.9683},
    {"epoch": 2.0, "loss": 1.7162 },
    {"epoch": 3.0, "loss": 1.4691 },
    {"epoch": 4.0, "loss":  1.3312 },
    {"epoch": 5.0, "loss":  1.2414 },

]

# Extract epochs and losses
epochs = [item["epoch"] for item in data]
losses = [item["loss"] for item in data]

# Create the plot
plt.figure(figsize=(8, 5))  # Set the figure size
plt.bar(epochs, losses, color='black' )  # Plot the data with markers and line
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Loss vs Epoch from Experiment 1")
plt.grid(True)  # Add grid lines for better readability

# Display the plot
plt.show()

import matplotlib.pyplot as plt

# Data from the provided JSON
data2 = [
    {"epoch": 1.0, "loss":  1.9006 },
    {"epoch": 2.0 ,"loss": 1.5791},
    {"epoch": 3.0, "loss":1.3147},
    {"epoch": 4.0, "loss": 1.1739 },
    {"epoch": 5.0, "loss":  1.17 },


]

# Extract epochs and losses
epochs = [item["epoch"] for item in data2]
losses = [item["loss"] for item in data2]

# Create the plot
plt.figure(figsize=(8, 5))  # Set the figure size
plt.bar(epochs, losses, color='black' )
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Loss vs Epoch from Experiment 2")
plt.grid(True)  # Add grid lines for better readability

# Display the plot
plt.show()

import matplotlib.pyplot as plt

# Data from the provided JSON
data3 = [
    {"epoch": 1.0, "loss":  1.8001 },
    {"epoch": 2.0 ,"loss": 1.5733},
    {"epoch": 3.0, "loss": 1.2581},
    {"epoch": 4.0, "loss": 1.1565 },
    {"epoch": 5.0, "loss":  1.1191 },


]

# Extract epochs and losses
epochs = [item["epoch"] for item in data3]
losses = [item["loss"] for item in data3]

# Create the plot
plt.figure(figsize=(8, 5))  # Set the figure size
plt.bar(epochs, losses, color='black' )
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Loss vs Epoch from Experiment 3")
plt.grid(True)  # Add grid lines for better readability

# Display the plot
plt.show()

import matplotlib.pyplot as plt

# Data from the provided JSON
data4 = [
    {"epoch": 1.0, "loss":  1.799 },
    {"epoch": 2.0 ,"loss": 1.5895},
    {"epoch": 3.0, "loss": 1.2106},
    {"epoch": 4.0, "loss": 1.1518 },
    {"epoch": 5.0, "loss":  1.0777 },


]

# Extract epochs and losses
epochs = [item["epoch"] for item in data4]
losses = [item["loss"] for item in data4]

# Create the plot
plt.figure(figsize=(8, 5))  # Set the figure size
plt.bar(epochs, losses, color='black' )
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Loss vs Epoch from Experiment 4")
plt.grid(True)  # Add grid lines for better readability

# Display the plot
plt.show()

import matplotlib.pyplot as plt

# Data from the provided JSON
d = [
    {"epoch": 1.0, "loss": 4.0092},
    {"epoch": 2.0, "loss": 3.6096},
    {"epoch": 3.0, "loss": 3.75045},

]

# Extract epochs and losses
epochs = [item["epoch"] for item in d]
losses = [item["loss"] for item in d]

# Create the plot
plt.figure(figsize=(8, 5))  # Set the figure size
plt.bar(epochs, losses, color='black' )
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training Loss vs Epoch in Experiment 10 ")
plt.grid(True)  # Add grid lines for better readability

# Display the plot
plt.show()

import matplotlib.pyplot as plt

# Data from the provided JSON
d2 = [
    {"epoch": 1.0, "loss": 1.677},
    {"epoch": 2.0, "loss": 1.5238},
    {"epoch": 3.0, "loss": 1.3326},
    {"epoch": 4.0, "loss": 1.286},
     {"epoch": 5.0, "loss": 1.46790},

]

# Extract epochs and losses
epochs = [item["epoch"] for item in d2]
losses = [item["loss"] for item in d2]

# Create the plot
plt.figure(figsize=(8, 5))  # Set the figure size
plt.bar(epochs, losses, color='black' )
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training Loss vs Epoch in Experiment 8 ")
plt.grid(True)  # Add grid lines for better readability

# Display the plot
plt.show()

import matplotlib.pyplot as plt

# Data from the provided JSON
d3 = [
    {"epoch": 1.0, "loss": 1.7983},
    {"epoch": 2.0, "loss": 1.2841},
    {"epoch": 3.0, "loss": 1.1299},
    {"epoch": 4.0, "loss": 1.102},
     {"epoch": 5.0, "loss": 1.1019},

]

# Extract epochs and losses
epochs = [item["epoch"] for item in d3]
losses = [item["loss"] for item in d3]

# Create the plot
plt.figure(figsize=(8, 5))  # Set the figure size
plt.bar(epochs, losses, color='black' )
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title(" Loss vs Epoch in Experiment 5 ")
plt.grid(True)  # Add grid lines for better readability

# Display the plot
plt.show()

import matplotlib.pyplot as plt

# Data from the provided JSON
d4= [
    {"epoch": 1.0, "loss": 1.7189},
    {"epoch": 2.0, "loss": 1.3235},
    {"epoch": 3.0, "loss": 1.1164},
    {"epoch": 4.0, "loss": 1.1148},
     {"epoch": 5.0, "loss": 1.1019},

]

# Extract epochs and losses
epochs = [item["epoch"] for item in d4]
losses = [item["loss"] for item in d4]

# Create the plot
plt.figure(figsize=(8, 5))  # Set the figure size
plt.bar(epochs, losses, color='black' )
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title(" Loss vs Epoch in Experiment 6 ")
plt.grid(True)  # Add grid lines for better readability

# Display the plot
plt.show()

import matplotlib.pyplot as plt
# Data from the provided JSON
d5= [
    {"epoch": 1.0, "loss": 1.7452},
    {"epoch": 2.0, "loss": 1.6756},
    {"epoch": 3.0, "loss": 1.6332},
    {"epoch": 4.0, "loss": 1.6032},
     {"epoch": 5.0, "loss": 1.6364},

]

# Extract epochs and losses
epochs = [item["epoch"] for item in d5]
losses = [item["loss"] for item in d5]

# Create the plot
plt.figure(figsize=(8, 5))  # Set the figure size
plt.bar(epochs, losses, color='black' )
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title(" Loss vs Epoch in Experiment 9 ")
plt.grid(True)  # Add grid lines for better readability

# Display the plot
plt.show()

#plot Rouge Score
import matplotlib.pyplot as plt
# Data from the provided JSON
d8= [
    {"name": "Timalsina", "rouge1": 15.74, "rouge2":3.29 , "rougel":15.21},
    {"name": "XLsum", "rouge1":26.6547  , "rouge2": 10.2479, "rougel":24.2847},
    {"name": "Ekantipur", "rouge1":16.497 , "rouge2":5.583 , "rougel":15.20},
    {"name": "NepGlUE", "rouge1":25.349 , "rouge2":10.8975 , "rougel":23.2604}
]

 # Data
rouge_scores = {'ROUGE-1': 20, 'ROUGE-2': 15, 'ROUGE-L': 10}

# Extract epochs and losses
model = [item["name"] for item in d8]
rougeone = [item["rouge1"] for item in d8]
rougetwo = [item["rouge2"] for item in d8]
rougeyell = [item["rougel"] for item in d8]

# Create the plot
plt.figure(figsize=(8, 5))  # Set the figure size
plt.bar(model.keys(), rouge_scores.values())

plt.xlabel("model")
plt.ylabel("rougue value")
plt.title(" Rouge values  ")
plt.grid(True)  # Add grid lines for better readability

# Display the plot
plt.show()

import matplotlib.pyplot as plt

# Data
rouge_scoresa = {'ROUGE-1': 20, 'ROUGE-2': 15, 'ROUGE-L': 10}
rouge_scoresb = {'ROUGE-1': 30, 'ROUGE-2': 25, 'ROUGE-L': 20}
rouge_scoresc = {'ROUGE-1': 40, 'ROUGE-2': 35, 'ROUGE-L': 30}
# Create a bar chart
plt.bar(rouge_scoresa.keys(), rouge_scoresa.values(), color = "blue")
plt.bar(rouge_scoresb.keys(), rouge_scoresb.values())
plt.bar(rouge_scoresc.keys(), rouge_scoresc.values())
# Add labels and title
plt.xlabel('ROUGE Metric')
plt.ylabel('Score')
plt.title('Comparison of ROUGE Scores')

# Show the chart
plt.show()

import matplotlib.pyplot as plt

# Sample data (replace with your actual data)
modelss= ['xlsum', 'nepGlue', 'timalsina', 'ekantipur']
rouge1 = [30, 45, 20,10 ]  # Apples
rouge2 = [25, 30, 15, 77]  # Tomatoes
rougel = [50, 25,30, 50]#



# Define positions for each group of bars
index = range(len(modelss))

# Create the grouped bar chart
plt.figure(figsize=(8, 6))  # Adjust figure size as needed
plt.bar(index, rouge1,  label='Rouge1')
plt.bar(index, rouge2, label='rouge2')
plt.bar(index, rougel,  label='rougel')

# Set labels and title
plt.xlabel('model')
plt.ylabel('rouge')
plt.title('Comparison of Rouge Scores')

# Set x-axis positions for each country
#plt.xticks([p + bar_width / 2 for p in index], modelss)

# Add legend
plt.legend()

# Show the chart
plt.show()

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


# Data
months = ['January', 'February', 'March', 'April', 'May', 'June']
shade_1_sales = [2000, 3000, 4000, 5000, 1000, 2000]
shade_2_sales = [5000, 4000, 3000, 2000, 4000, 1000]
shade_3_sales = [1000, 2000, 1000, 3000, 2000, 4000]
shade_4_sales = [4000, 1000, 2000, 5000, 3000, 1000]

# Create a bar graph
plt.figure(figsize=(10, 6))  # Adjust the figure size as needed

# Create multiple bars at each position
x = np.arange(len(months))  # Create x-axis positions
width = 0.35  # Width of each bar

plt.bar(x - width/2, shade_1_sales, width, label='Shade 1')
plt.bar(x, shade_2_sales, width, label='Shade 2')
plt.bar(x + width/2, shade_3_sales, width, label='Shade 3')
plt.bar(x + width, shade_4_sales, width, label='Shade 4')

# Set labels and title
plt.xlabel('Month')
plt.ylabel('Sales (in units)')
plt.title('Sales of Different Shades over Months')

# Set x-axis tick positions and labels
plt.xticks([p + width/2 for p in x], months)

# Rotate x-axis labels for better readability
plt.xticks(rotation=45)

# Add legend
plt.legend()

# Show the chart
plt.grid(axis='y')  # Add gridlines for better readability
plt.tight_layout()
plt.show()