# -*- coding: utf-8 -*-
"""copy_finetuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gcL6PPNSQZ7Szpecb-aRsbtYhHqMLUBL
"""

pip install bitsandbytes accelerate transformers ipywidgets datasets pandas numpy tqdm

import pandas as pd
import numpy as np
from tqdm import tqdm
import torch

from tokenizers import SentencePieceUnigramTokenizer, processors

from transformers import BartTokenizerFast

fast_tokenizer = BartTokenizerFast(
    tokenizer_file = "/content/tokenizer (1).json",
    model_max_length = 1000,
    bos_token = "<cls>",
    eos_token = "<sep>",
    unk_token = "<unk>",
    pad_token = "<pad>",
    mask_token = "<mask>",
)

from huggingface_hub import login
login()

from transformers import BartForConditionalGeneration, AutoModelForSeq2SeqLM


model = AutoModelForSeq2SeqLM.from_pretrained("Bijayab/ekantipur90_nep_summ_BART",
                                              max_length = 1000,
                                              do_sample=True,
                                              num_beams = 3,
                                              )

sentence = """सांसदको लोगो छोडेर सिलाम साक्मामा मात्र भेटिएपछि उनलाई जिज्ञाशा राखियो ।उनले किराती परम्परामा सिलाम साक्माको महत्त्वबारे उल्लेख गर्दै 'कान्तिपुर' को स्मरणका लागि 'सिलाम साक्मा' लगाएको तस्बिर खिच्न आग्रह गरे । स्मरणका लागि भन्दै खिचाएको त्यही तस्बिर जस्तै उनले राजनीतिमा खेलेको भूमिका र योगदान पनि अब इतिहासको गर्भमा पुगेको छ ।

अब शान्त, शालीन र भद्र राजनीतिज्ञका रूपमा धेरैले चिन्ने तिनै सादगी सुवासचन्द्र नेम्वाङको भौतिक शरीर अब रहेन । सोमबार मध्यराति उनको निधन भयो । उनको निधनप्रति धेरै राजनीतिज्ञ, सामाजिक क्षेत्रका व्यक्ति लगायतले गहिरो शोक व्यक्त गरेका छन् । सक्रिय राजनीतिक गतिविधिमा संलग्न रहँदा रहँदै भएको उनको निधनले एमालेजन मात्र होइन धेरैलाई स्तब्ध बनाएको छ । नेम्वाङप्रतिका श्रद्धाञ्जलीका शब्द र तस्बिरले सामाजिक सञ्जालहरू पनि शोकमय भएका छन् ।

इलामको सुन्तलाबारीमा २००९ सालमा जन्मिएका नेम्वाङको ७० वर्षे जीवनका पछिल्ला ५० वर्ष भने सक्रिय राजनीतिमा बिते । कानुनी पृष्टभूमिसहित पार्टी राजनीतिमा सक्रिय रहेका नेम्वाङ संविधानसभाबाट संविधान जारी गर्ने हरेक घटनाक्रममा एक प्रत्यक्ष साक्षी र निर्णयकर्ता हुन् । संविधानसभा, सभामुख र संसद् भन्नेबित्तिकै त्यसको पर्यायवाचीका रूपमा नाम लिइने व्यक्ति थिए, नेम्वाङ । दुइटै संविधानसभाका अध्यक्ष नेम्वाङले संविधानसभाबाट संविधान जारी गर्ने क्रममा खेलेको भूमिका स्मरणीय छ ।"""

inputs = fast_tokenizer(sentence, max_length=1000, return_tensors="pt")

summary_ids = model.to('cuda').generate(inputs["input_ids"].to('cuda'), min_length=0, max_length=256, num_beams = 3, do_sample = True)

summary_ids

fast_tokenizer.decode(summary_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)

"""# Test Summary Generation"""

import pandas as pd
from tqdm import tqdm

df = pd.read_csv('/content/test_prediction.csv')

def apply_summarization(text):
  inputs = fast_tokenizer(text, max_length=1000, return_tensors="pt")
  summary_ids = model.to('cuda').generate(inputs["input_ids"].to('cuda'), min_length=0, max_length=256, num_beams = 3, do_sample = True)
  return fast_tokenizer.decode(summary_ids[0], skip_special_tokens=True, clean_up_tokenization_spaces=False)

tqdm.pandas(desc="Applying function")
df['summary_csv_file'] = df['text'].progress_apply(apply_summarization)

df

df.to_csv('final_test_prediction_summarydata.csv',encoding='utf-8',index=False)

!pip install rouge_score nltk evaluate

import evaluate

rouge = evaluate.load("rouge")

df = pd.read_csv("final_test_prediction_summarydata.csv")

results = rouge.compute(predictions=df.iloc[:,3].values,
                        references=df.iloc[:,1].values,
                        rouge_types = ['rouge1', 'rouge2', 'rougeL'],
                        use_aggregator=True,
                        tokenizer=lambda x: x.split())
results

